### ISSUE TITLE
Error: cannot find module public/assets.json

### ISSUE THREAD

**Issue by MercStills** [Paqmind/react-ultimate#100]
Was public/assets.json supposed to be fetched during the build process?  Any suggestions on how to obtain the assets?

**Comment by ivan-kleshnin** [comment]
`public/assets.json` is a file created by Webpack on production build which holds a build specs. 

As far as I can recall, the only place which makes it is:

**webpack.config-prod.js**
```js
function () {
      this.plugin("done", function (stats) {
        let jsonStats = stats.toJson({
          chunkModules: true,
        });
        jsonStats.publicPath = "/public/";
        Fs.writeFileSync(
          Path.join(PUBLIC_DIR, "assets.json"), // <--------------------<<<<
          JSON.stringify(jsonStats.assetsByChunkName)
        );
      });
    },
```

So it supposed to be built by this custom plugin in the process of `npm run build`.
