### ISSUE TITLE
Can not install.....

### ISSUE THREAD

**Issue by cheneddie** [Paqmind/react-ultimate#104]
![1489412104247](https://cloud.githubusercontent.com/assets/17492557/23856563/0e7f19e2-0835-11e7-965b-57ef19ce7b5d.jpg)

**Comment by ivan-kleshnin** [comment]
@cheneddie yes. Sorry 😞  this repo is quite broken a.t.m.
I started a total rewrite some time ago but my plans were interrupted then.
The best full-blown React example right now is https://phenomic.io/
I would advice to inspect how it's made instead.
