### ISSUE TITLE
Consider Mori instead of Immutable

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-ultimate#43]
Subj.

**Comment by ivan-kleshnin** [comment]
Auch. All this immutable stuff pollutes the code so much that bug are **more** likely rather than **less**.
Will drop it completely.

**Comment by ivan-kleshnin** [comment]
Also consider https://github.com/rtfeldman/seamless-immutable

**Comment by alexmingoia** [comment]
An important distinction to note is that immutable data != single state tree (ala Baobab). It would be great if seamless-immutable had a similar cursor implementation as baobab where you could easily navigate an immutable tree.

**Comment by ivan-kleshnin** [comment]
> An important distinction to note is that immutable data != single state tree (ala Baobab). It would be great if seamless-immutable had a similar cursor implementation as baobab where you could easily navigate an immutable tree.

Hi Alex! Not sure I'm totally following your words. We are generally talking about cursors when we're subscribing on updates of some data. But immutable data can't have updates by definition. So what do you mean by "navigate an immutable tree"? Or maybe you're talking about the possibility to have more comfortable `get-in` and `set-in` functions to access deeply nested data? 

https://twitter.com/BrandonBloom/status/595694691674370051

There is a lens concept http://ramdajs.com/docs/#lens or https://github.com/Paqmind/data-lens to workaround this. Anyway, I'd like you to rephrase this for me.

**Comment by ivan-kleshnin** [comment]
**Ramda** and **Seamless-Immutable** are mutually exclusive (funcs vs methods). 
Gonna stay with the first for now.
