### ISSUE TITLE
Try other background for header

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-ultimate#48]
This one but inversed:
http://subtlepatterns.com/small-steps/

**Comment by scabbiaza** [comment]
Let's compare

Original:
http://puu.sh/hDffE.png

Inverted new bg:
http://puu.sh/hDfgB.png

Original darker:
http://puu.sh/hDfop.png

I think have a darker bg is a right direction, but new patter is no noise from my point of view.

**Comment by ivan-kleshnin** [comment]
Ok, current one is better, others lack contrast. Let's go further.
