### ISSUE TITLE
Watch for images folder doesn't work

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-ultimate#49]
This issue is related to the pathes, look at this commit:
https://github.com/Paqmind/react-ultimate/commit/df8f558fed865a5ef61ed1e7c79629d12ed25d90

After I change path
`Gulp.watch("./frontend/images/**/*", ["dist-images"]);` 
to 
`Gulp.watch("frontend/images/**/*", ["dist-images"]);`

it started working fine, for all cases.

I also added clear task for images, otherwise `public/images` will contain a lot of unuseful files after some time.

**Comment by ivan-kleshnin** [comment]
Checked. I also have this problem on my machine.

**Comment by ivan-kleshnin** [comment]
Please don't update comments if you want me to see it. Updates don't cause notifications.
