### ISSUE TITLE
Live reload stopped working

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-ultimate#56]
Need to trace the cause first.

**Comment by scabbiaza** [comment]
`--inline` was missed  in `package.json`:
```
"scripts": {
    "dev": "webpack-dev-server --config webpack.config-dev.js --progress --colors --port 2992 --inline",
```

Don't know for what reasons. After I added it back, reload starts working again.

**Comment by ivan-kleshnin** [comment]
Thank you. It's connected with what I've said you about those entry points which everyone uses except Webpack. Remember?

Documentation is poor, but something is getting clearer:
https://github.com/webpack/webpack-dev-server/blob/dd6da4fc827aa236b3c69687eb55b9a72d7e955b/example/README.md#inlined-mode
