### ISSUE TITLE
CRUD bugs

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-ultimate#65]
I will put it all together in one issue

*Add robot*

If you click on "Submit" without filling fields / or with filling only one field, you will see next
http://puu.sh/hSUZY.png

Looks like this alert should not be there.
And "Submit" button is in "disabled" status after this actions and doesn't change it. 
So there is no ability to continue working with this form.

What should "Reset" button do? I don't understand or it doesn't work: I expect it to reset form field values to previous values.

*Delete robot*

Sorry, deleting has an error:
`Uncaught (in promise) TypeError: query.sorts.join is not a function at formatQueryForAxios`
But the robot was deleted!

*Edit robot*
Works fine! The only one question is the "Reset" button

*Add monster*
Monster was aded, but I got an error while redirecting after creating
`http://localhost:3000/api/robots/50635674-551d-40b5-a30f-21eda7443b1c 404 (Not Found)` 

*Edit monstr*

Got 400
`PUT http://localhost:3000/api/robots/7c8d7f8a-c538-4359-9d68-843e6b58770d 400 (Bad Request)`

```
Your HTTP request is not valid!
Errors
"manufacturer" is required
```

After this error monstr list wasn't work

*Delete monstr*

Also got some error:
`Uncaught (in promise) TypeError: Cannot set property 'filter[cc7f0583-1d7a-4faa-bcad-fdeb3e6190c3]' of undefined`

**Comment by scabbiaza** [comment]
Lists works very well, and perpage, pagination, sorting and filters also work nice!
The only one very small thing that I found, is that in some cases by changing perpage, active page is not highlighting in pagination.

Steps to reproduce: 
1. Set perpage=3 and go to the page 10
2. Set perpage=5 and you will see that pagination is not showing active item

I supposed it's because of different offsets.

**Comment by ivan-kleshnin** [comment]
> Looks like this alert should not be there.

It should. I will good loking model-based `Alert` there later.

> And "Submit" button is in "disabled" status after this actions and doesn't change it. 
So there is no ability to continue working with this form.

It's not true. After fixing the errors, Submit is unblocked. 
There was errors with Reset button in both Add forms which I've fixed with a little hack for now.

**Comment by ivan-kleshnin** [comment]
> What should "Reset" button do? I don't understand or it doesn't work: I expect it to reset form field values to previous values.
It does reset and comparing to old-school HTML reset it really resets form to the model value in case of edit and to the default empty values in case of add.

**Comment by ivan-kleshnin** [comment]
> Sorry, deleting has an error:
Uncaught (in promise) TypeError: query.sorts.join is not a function at formatQueryForAxios
But the robot was delete!

This helped me to discover some dangerous bugs and fix them. Thank you!

**Comment by ivan-kleshnin** [comment]
> Add monster
Monster was aded, but I got an error while redirecting after creating
http://localhost:3000/api/robots/50635674-551d-40b5-a30f-21eda7443b1c 404 (Not Found)

It was just a typo in string constant (`robot-detail` vs `monster-detail`). Fixed!

**Comment by ivan-kleshnin** [comment]
Thank you very much. Now it's much better :+1:
