### ISSUE TITLE
Webspeed tests

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-ultimate#66]
Before new release
http://www.webpagetest.org/result/150519_PB_13J3/
![webpagetest # 1](http://puu.sh/hTcq0.png)

http://www.webpagetest.org/result/150519_RC_13MZ/
![webpagetest # 2](http://puu.sh/hTda9.png)

Google PageSpeed Results
![Google PageSpeed Results](http://puu.sh/hTbJk.png)

**Comment by ivan-kleshnin** [comment]
I'm going to re-measure this after finishing Webpack.

**Comment by ivan-kleshnin** [comment]
Closed as outdated.
