### ISSUE TITLE
Bug with alerts

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-ultimate#67]
Manual removal should not cause huge delay with auto-removal.

**Comment by scabbiaza** [comment]
Fixed in this commit:
https://github.com/Paqmind/react-ultimate/commit/35d9d648e1a4f7cebb4bbc6b5938f0eef0dbd20c

Merged in master

**Comment by scabbiaza** [comment]
Updated master with last changes

**Comment by ivan-kleshnin** [comment]
Fixed
