### ISSUE TITLE
Simpler require paths

### ISSUE THREAD

**Issue by vjpr** [Paqmind/react-ultimate#72]
There is a module called [add-module-path](https://www.npmjs.com/package/app-module-path) that allows you to specify `NODE_PATH` programmatically. Less moving paths than the symlink thing.

A discussion of all approaches can be found here: https://gist.github.com/branneman/8048520

**Comment by ivan-kleshnin** [comment]
I saw that thread and I think symlinks are the best solution. 
1) They are compatible with Webpack and any other bundle systems upfront.
2) They are compatible with IDE quick navigation.
Everything just works without magic.
