### ISSUE TITLE
Rethink architecture concepts

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-ultimate#78]
#### type

Independent. 

JS types

#### validator 

Depends on **type**.

1. Converts input types
2. Provides validation errors

#### model

Depends on **validator**.

1. Converts input types (with **validator**)
2. Raises an error for invalid input
3. Generate defaults for some optional input

*This violates the Single Responsibility principle.*

#### maker

Depends on **model**.

1. Generates values for required model input

#### type

Independent.

JS types ([Tcomb](https://github.com/gcanti/tcomb) types) + Custom types

1. Raises an error for invalid input

#### parser

Independent.

1. Converts input types (with [Globalize](https://github.com/jquery/globalize)) 

#### maker

Depends on **model**.

1. Generates values for all inputs

**Comment by ivan-kleshnin** [comment]
Consequences:

1. Remove JOI dependency
2. Add TComb and Globalize dependency
3. Remove **model** concept. `User` will be a Tcomb type.
4. Remove **generate value for optional input** concept.

**Comment by scabbiaza** [comment]
:+1:

**Comment by ivan-kleshnin** [comment]
Implemented.
