### ISSUE TITLE
Error on starting the app

### ISSUE THREAD

**Issue by philohelp** [Paqmind/react-ultimate#99]
I cant figure whats wrong here, sadly because the app looked great...

```
70% 1/1 build moduleshttp://localhost:2992/
webpack result is served from http://localhost:2992/public/
content is served from /Users/macbook/ultimate
 40% 3/6 build modules/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			            ^

Error: No module factory available for dependency type: CommonJsRequireDependency
    at Compilation.addModuleDependencies (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:181:20)
    at Compilation.processModuleDependencies (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:170:7)
    at /Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:320:12
    at /Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:140:10)
    at DependenciesBlock.<anonymous> (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModule.js:115:10)
    at DependenciesBlock.onModuleBuild (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/macbook/ultimate/node_modules/webpack-dev-server/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
```

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! react-starter@0.1.0 dev: `source .development; webpack-dev-server --config webpack.config-dev.js --progress --colors --port 2992 --inline`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-starter@0.1.0 dev script 'source .development; webpack-dev-server --config webpack.config-dev.js --progress --colors --port 2992 --inline'.
npm ERR! This is most likely a problem with the react-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     source .development; webpack-dev-server --config webpack.config-dev.js --progress --colors --port 2992 --inline
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/macbook/ultimate/npm-debug.log

```

**Comment by ivan-kleshnin** [comment]
@philohelp it's strange. I never saw such error. Can't even guess what to do in this case. Googling doesn't give an answer. I would try to change webpack / webpack-dev-server version as it seems like a bug there.

**Comment by gaea44** [comment]
I,

after running both `npm run build` and `npm run node`

What's the URL to check the app??
I tried `localhost:3000` but it gives me a simple blank page.

when I check the code, I have no index.html anywhere (other than node_modules folder).
Do I miss something ?

For info, `npm run build` show me a `sh: 1: source: not found`, but I can launch `source .production`  directly from the shell.

The same goes for launching dev environment,
What is the URL ?

Thanks in advance.

**Comment by ivan-kleshnin** [comment]
@gaea44  see https://github.com/Paqmind/react-ultimate/issues/98

**Comment by gaea44** [comment]
Hi,

thanks for redirecting me, but even when I tried localhost:3000, I dont get it to work.
localhost:3000 sais "connexion failed".

I have both `npm run dev` and `npm run nodemon`.

**Comment by ivan-kleshnin** [comment]
Did you wait for Nodemon listening event?

If you see something like `2016-03-21 01:29:57 INFO Listening on port 3000` in console and browser still responds with connection error at `localhost:3000` I can't help because it's not an app problem.

**Comment by gaea44** [comment]
Hi,

I don't see anything about port 3000 in console.
Here is what's console show for me 

> $ npm run nodemon

> react-starter@0.1.0 nodemon /home/me/workspace/react-ultimate
source .development; nodemon backend/server.js
**sh: 1: source: not found**
[nodemon] 1.9.1
[nodemon] reading config /home/me/workspace/react-ultimate/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /home/me/workspace/react-ultimate/.git/**/* .nyc_output .sass-cache bower_components coverage /home/me/workspace/react-ultimate/node_modules/**/* /home/me/workspace/react-ultimate/.git/**/* node_modules/**/node_modules
[nodemon] watching: /home/me/workspace/react-ultimate/backend/**/* /home/me/workspace/react-ultimate/shared/**/*
[nodemon] watching extensions: js,html
[nodemon] starting `babel-node --stage 0 backend/server.js`
[nodemon] child pid: 10040
[nodemon] watching 48 files

**Comment by ivan-kleshnin** [comment]
Probably because of 

> sh: 1: source: not found

Your OS does not allow to load environment vars like I do here. 
So `server.js` gets no `3000` port. You can update 

**backend/server.js**

```diff
- server.listen(process.env.HTTP_PORT);` 
+ server.listen(process.env.HTTP_PORT || 3000);` 
```

Or try to run directly `source .development; nodemon backend/server.js` instead of `npm run dev`.

It would be cool if you could advice me how to update npm script properly to be more OS agnostic.
I don't have time to investigate this further at this moment.
